version: '3'



services:
  db:
    build: ./db
    
    environment:
       POSTGRES_USER: chatuser
       POSTGRES_PASSWORD: chatpass
       POSTGRES_DB: chatdb

    volumes:
      - ./db:/docker-entrypoint-initdb.d 





  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin  
      PGADMIN_DEFAULT_SERVER: db  
      PGADMIN_DEFAULT_SERVER_PORT: 5432  
      PGADMIN_DEFAULT_SERVER_DB: chatdb  
      PGADMIN_DEFAULT_SERVER_USERNAME: chatuser 
      PGADMIN_DEFAULT_SERVER_PASSWORD: chatpass  
    ports:
      - "8082:80"