version: '3'


services:
  bd:

     image: mysql:latest
     volumes:
      - "./bd:/docker-entrypoint-initdb.d" 
     environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phpdocker
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
     ports:
      - "3306:3306"
    
  php:
    
    build: ./php
    volumes:
      - "./php:/var/www/html"  
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - bd


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: bd
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
  