apiVersion: v1
kind: Pod
metadata:
  name: appp
  labels:
    name: appp
spec:
  containers:
  - name: appp
    image: khadijaj/htmlm-k8s-services-index:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
