version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:5000

  website:
    image: php:8.2-apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5002:80
    depends_on:
      - product-service

